### PR TITLE
Attempt to automate deleting stale branches

### PR DESCRIPTION
**Pull request by sparkles-laurel**
title is self-describing

### CODE REVIEW

**Review by SatoCodingStuff — APPROVED** [review]
yeah it is. LGTM!

**Comment by SatoCodingStuff** [comment]
oh no

**Comment by SatoCodingStuff** [comment]
looks like it does not work

**Comment by sparkles-laurel** [comment]
Run git branch -d delete-stale-branches
  git branch -d delete-stale-branches
  shell: /usr/bin/bash -e {0}
fatal: not a git repository (or any of the parent directories): .git
Error: Process completed with exit code 128.

:nvidia:

**Comment by sparkles-laurel** [comment]
Imma look into this
seems like we lack a .git directory

**Comment by sparkles-laurel** [comment]
```
[sparky@cehennet popcorn]$ ls -lA
total 216
drwxr-xr-x 2 sparky sparky   4096 Jul 17 22:00 .cargo
drwxr-xr-x 8 sparky sparky   4096 Jul 17 22:00 .git
drwxr-xr-x 3 sparky sparky   4096 Jul 16 15:58 .github
-rw-r--r-- 1 sparky sparky     18 Jul 16 15:58 .gitignore
-rw-r--r-- 1 sparky sparky 167055 Jul 16 16:01 2023-07-16-160122_1366x768_scrot.png
-rw-r--r-- 1 sparky sparky    716 Jul 17 22:00 Cargo.toml
-rw-r--r-- 1 sparky sparky   1076 Jul 16 15:58 LICENSE
-rw-r--r-- 1 sparky sparky    409 Jul 17 22:00 Makefile
-rw-r--r-- 1 sparky sparky   3718 Jul 16 15:58 README.md
-rw-r--r-- 1 sparky sparky   1147 Jul 17 22:00 SECURITY.md
drwxr-xr-x 2 sparky sparky   4096 Jul 17 22:00 arch
drwxr-xr-x 2 sparky sparky   4096 Jul 17 22:00 locale
drwxr-xr-x 4 sparky sparky   4096 Jul 17 22:00 src
drwxr-xr-x 2 sparky sparky   4096 Jul 17 22:00 tests
```
we do have a `.git` directory

**Comment by sparkles-laurel** [comment]
can we instead use a hook?

**Comment by SatoCodingStuff** [comment]
i guess so

**Pull request merged**
