### PR TITLE
Update rust.yml

### LINKED ISSUE #14: CI issue: we don't have rust-src on CI
```
error: "/home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/Cargo.lock" does not exist, unable to build with the standard library, try:
        rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu
Error: Process completed with exit code 101.
```

can we install the said component on CI?

### PR DESCRIPTION
**Pull request by SatoCodingStuff**
trying to fix #14

### CODE REVIEW

**Review by sparkles-laurel — CHANGES_REQUESTED** [review]
I don't think it will work, honestly. Imma check when I'm home

**Comment by SatoCodingStuff** [comment]
Okie

**Comment by electron271** [comment]
shouldnt this be before the compilation and stuff

**Comment by SatoCodingStuff** [comment]
yeah i tried to fix this but then sparky said that its not gonna work so i just dropped it

**Comment by SatoCodingStuff** [comment]
seems to be mergeable

**Review by sparkles-laurel — APPROVED** [review]
I think ıt should work

**Pull request merged**
