### PR TITLE
fix workflow bcz people were high when making it

### PR DESCRIPTION
**Pull request by HackedOS**
@SparkySimp @SatoTsukasaCode were high when making workflows

### CODE REVIEW

**Comment by sparkles-laurel** [comment]
i was drunk ok?
drunk with air change

**Comment by sparkles-laurel** [comment]
uhhh @HackedOS are you sure about that i should approve this

**Comment by HackedOS** [comment]
> uhhh @HackedOS are you sure about that i should approve this

sure about what

**Comment by sparkles-laurel** [comment]
look at all the failing checks

**Comment by HackedOS** [comment]
they are supposed to fail, fix the errors so it doesnt fail easy

**Comment by HackedOS** [comment]
i can make them not fail if u want

**Comment by electron271** [comment]
give me a bit

**Review by sparkles-laurel — APPROVED** [review]
lgtm

**Comment by sparkles-laurel** [comment]
done

**Pull request merged**
