### PR TITLE
Extracted code to functions

### PR DESCRIPTION
**Pull request by janTatesa**
Just to improve modularity , I extracted some code to separate functions. Please note that print_with colors macro automatically calls set_color!

### CODE REVIEW

**Comment by HackedOS** [comment]
fix merge conflicts pls @TadoTheMiner

**Comment by SatoCodingStuff** [comment]
fix conflict please.

**Comment by janTatesa** [comment]
how do you resolve the config

**Comment by janTatesa** [comment]
*
conflict

**Comment by SatoCodingStuff** [comment]
click the button below the conversation that says "Resolve conflicts"

**Comment by janTatesa** [comment]
And then?

**Comment by janTatesa** [comment]
Okay now its doing checks

**Comment by janTatesa** [comment]
done

**Review by sparkles-laurel — APPROVED** [review]
lgtm

**Review by electron271 — APPROVED** [review]
lgtm

**Comment by electron271** [comment]
beat me to it :sob:

**Comment by sparkles-laurel** [comment]
actually, @TadoTheMiner, I'd love to see it using ASCII terminal control codes

**Pull request merged**
