### PR TITLE
Some new stuff.

### PR DESCRIPTION
**Pull request by mrrpnya**
- Documented functions
- Graceful kernel panic handler
- VGA Buffer additions:
 - Clear screen, with color
 - Set color
- Some memory functions added (memcpy, memset) to get things working correctly

### CODE REVIEW

**Comment by SatoCodingStuff** [comment]
seems to a github issue, works fine in my testing

**Comment by SatoCodingStuff** [comment]
@SparkySimp are we gonna merge this?

**Comment by sparkles-laurel** [comment]
Eh why do the checks fail

**Comment by SatoCodingStuff** [comment]
seems to be a bad config in the github server, works fine in my server + local machine

**Comment by sparkles-laurel** [comment]
im going to merge it seems like we have an infrastructure bug
image

**Review by sparkles-laurel — COMMENTED** [review]
Thank you so much, there seems to be a faulty line in CI

**Pull request merged**
