### PR TITLE
fixed outdated README instructions

### PR DESCRIPTION
**Pull request by SatoCodingStuff**

### CODE REVIEW

**Comment by sparkles-laurel** [comment]
immediate merge no review required

**Comment by SatoCodingStuff** [comment]
yeah just fixed a quick something

**Comment by sparkles-laurel** [comment]
ehh doesn't `cargo run` invoke `qemu-system-x86_64` already

**Comment by SatoCodingStuff** [comment]
really?

**Review by sparkles-laurel — CHANGES_REQUESTED** [review]
L62: `cargo run` is sufficient

**Review by sparkles-laurel — APPROVED** [review]
now this should work

**Comment by sparkles-laurel** [comment]
wait for the checks please

**Pull request merged**
