### PR TITLE
code rewrite by hackos

### PR DESCRIPTION
**Pull request by electron271**
pr made on behalf of @HackedOS

### CODE REVIEW

**Comment by electron271** [comment]
we need to fix qemu being paused on startup with this binary

**Comment by SatoCodingStuff** [comment]
i am pushing a commit 1 sec

**Comment by SatoCodingStuff** [comment]
fixed.

**Comment by electron271** [comment]
thanks

**Comment by electron271** [comment]
changing colors needs to be added

**Review by SatoCodingStuff — APPROVED** [review]
lgtm rewrite!

**Pull request merged**
