### PR TITLE
added bootloader to the dependencies in cargo.toml

### PR DESCRIPTION
**Pull request by SatoCodingStuff**
needed to add bootloader manually everytime so i just added it to the toml. also its specified in here:
https://os.phil-opp.com/minimal-rust-kernel/#creating-a-bootimage

### CODE REVIEW

**Comment by SatoCodingStuff** [comment]
bruhhh

**Comment by SatoCodingStuff** [comment]
sigsegv is killing me

**Comment by SatoCodingStuff** [comment]
looks to be broken

**Comment by electron271** [comment]
to be honest with ya smells like a issue with our cargo conf

**Comment by SatoCodingStuff** [comment]
damn

**Comment by electron271** [comment]
give me 20 years

**Comment by SatoCodingStuff** [comment]
rip good luck

**Comment by SatoCodingStuff** [comment]
nice

**Comment by electron271** [comment]
accident

**Pull request merged**
