### PR TITLE
Merge branch 'main' of https://github.com/popcorn-kernel/popcorn

### PR DESCRIPTION
**Pull request by SatoCodingStuff**

### CODE REVIEW

**Comment by SatoCodingStuff** [comment]
changed println to libc_println

**Review by sparkles-laurel — CHANGES_REQUESTED** [review]
I'd like you to modify the macros' names in vga_buffer.rs, could you do that for me please?

**Comment by SatoCodingStuff** [comment]
yes

**Comment by sparkles-laurel** [comment]
So I'm going to approve once you do the necessary change

**Comment by SatoCodingStuff** [comment]
to what do you want me to change?

**Comment by sparkles-laurel** [comment]
libc_print[ln]

**Comment by SatoCodingStuff** [comment]
should be fixed now

**Pull request merged**
