### PR TITLE
Added more features for you to implement, I will try to implement it …

### PR DESCRIPTION
**Pull request by dx11enjoyer5534**
…later but for now ill just keep this, I didn't mess around with the actual functionality but yes

### CODE REVIEW

**Review by electron271 — CHANGES_REQUESTED** [review]
won't merge until functionality is implemented in order to avoid empty files which may be confusing for some people

**Comment by SatoTsukasaCode** [comment]
will this ever be worked on?

**Comment by dx11enjoyer5534** [comment]
too lazy lmfai

**Comment by dx11enjoyer5534** [comment]
i lost interest in operating systems

**Comment by electron271** [comment]
closed due to disinterest

**Pull request closed without merging**
