### PR TITLE
Minor Improvements, Prep for Paging

### PR DESCRIPTION
**Pull request by mrrpnya**
- Improved Panic screen to be able to display required fields for debugging of page systems:
image
 - Now has end-user instructions
 - Now has page fault code output
 - Now has memory address output
- Added page fault handler

### CODE REVIEW

**Comment by mrrpnya** [comment]
To safely accept an argument from the bootloader, _start has been replaced with kernel_main.

kernel_main can:
- Be named arbitrarily
- Accept a BootInfo struct from the bootloader

Also aligned a hex value in the above, and changed CODE_SEG to one too.

**Comment by sparkles-laurel** [comment]
so now you gotta describe why this is a draft

**Comment by SatoCodingStuff** [comment]
https://discord.com/channels/1128805264628383784/1128849819444715620/1130039077891215380

**Review by sparkles-laurel — APPROVED** [review]
Thank you so much again

**Pull request merged**
