### PR TITLE
Tidied up the code

### PR DESCRIPTION
**Pull request by janTatesa**
1. Removed the set_color and clearscreen macros since they did the same thing as functions
2. Added an userspace module which has the output submodule containing print println and print with colors macro and an user interface submodule. While yes, the macros do interact with vga_textbuffer, they do it through the print function, and only essential stuff with the textbuffer should be in vga_buffer in my opinion.

### CODE REVIEW

**Comment by janTatesa** [comment]
Somebody?

**Comment by janTatesa** [comment]
Now I put Writer in a separate submodule maybe i will put also buffer and char in buffer.rs. Question: Should the vga buffer constant be usize? I set it to usize but for cleanness, is it the best datatype for that?

**Comment by sparkles-laurel** [comment]
> Now I put Writer in a separate submodule maybe i will put also buffer and char in buffer.rs. Question: Should the vga buffer constant be usize? I set it to usize but for cleanness, is it the best datatype for that?

look, its a buffer size, native size type should be the most efficient and natural type for that thing.

also we really need to switch to 0xA0000 buffer (graphic mode) soon

**Comment by sparkles-laurel** [comment]
also umm lmk when it is ready for merge

**Comment by janTatesa** [comment]
@SparkySimp I am done, now i need to study.

**Review by sparkles-laurel — APPROVED** [review]
`low_level` sounds like a bad name but do we have any better name ideas in our hand atm? no i guess

**Comment by janTatesa** [comment]
@SparkySimp What about renaming lowlevel to kernelspace?

**Comment by sparkles-laurel** [comment]
sure @TadoTheMiner

**Pull request merged**
