### PR TITLE
added hackos to the readme.md

### PR DESCRIPTION
**Pull request by SatoCodingStuff**

### CODE REVIEW

**Comment by SatoCodingStuff** [comment]
do not merge, let me fix some stuff

**Review by electron271 — CHANGES_REQUESTED** [review]
image
formatting is looking weird

**Comment by SatoCodingStuff** [comment]
known, thats what i am fixing

**Comment by SatoCodingStuff** [comment]
still not working damn

**Comment by SatoCodingStuff** [comment]
FIXED. merging.

**Review by electron271 — APPROVED** [review]

**Pull request merged**
