### PR TITLE
Added print_with_colors macro and ran cargo fmt

### PR DESCRIPTION
**Pull request by janTatesa**
Basically print_with_colors is a more elegant way rather than running set_color every time. Also, I ran cargo fmt so its more elegant.

### CODE REVIEW

**Review by SatoCodingStuff — CHANGES_REQUESTED** [review]
fix issues please.

**Comment by electron271** [comment]
the issues have to do with the workflows being stupid

**Comment by SatoCodingStuff** [comment]
i see

**Comment by SatoCodingStuff** [comment]
again, please fix those issues.

**Comment by electron271** [comment]
@TadoTheMiner can you pull the new version of the workflow into your branch, should fix workflow failing

**Comment by electron271** [comment]
just did it manually

**Comment by electron271** [comment]
ok now it should work

**Review by SatoCodingStuff — APPROVED** [review]
LGTM~!

**Comment by electron271** [comment]
image

**Comment by janTatesa** [comment]
Nice. Thanks for pulling my first PR ever

**Comment by SatoCodingStuff** [comment]
congratulation!

**Pull request merged**
